version: '3.4'

services:
  interviewcheatsheet:
    image: interviewcheatsheet
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002
    environment:
      DEBUG: "true"
    env_file: ".env"